# Generated by Django 3.2.5 on 2026-03-11 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attedancelog',
            name='time_in',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='attedancelog',
            name='time_out',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
    ]
